{% set name = "legend-pygeom-hpges" %}
{% set version = "0.10.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/legend_pygeom_hpges-{{ version }}.tar.gz
  sha256: 22deb03471382e666e0a5720596a916589c1d8b98e2a28adda3ba6870ed3b82b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=77
    - setuptools-scm >=7
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba
    - pint !=0.24
    - pyg4ometry
    - dbetto
    - awkward

test:
  imports:
    - legendhpges
    - pygeomhpges
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Geometry management for LEGEND HPGe detectors
  home: https://github.com/legend-exp/legend-pygeom-hpges
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://legend-pygeom-hpges.readthedocs.io
  dev_url: https://github.com/legend-exp/legend-pygeom-hpges

extra:
  recipe-maintainers:
    - gipert
    - ManuelHu
